### ISSUE TITLE
Projects are not sorted

### ISSUE THREAD

**Issue by kassisaf** [ababyduck/afkcode.com#17]
Need to decide on a method for sorting projects.  Considering adding a date field to the model, along with a nullable "priority" column to override placement. i.e. Sort chronologically, then if priority exists order by that.

**Comment by ababyduck** [comment]
Resolved in b4ab4f73174531c0585a38074a0e0e21c3d81e7f

**Comment by kassisaf** [comment]
Resolved in 5db495313921e7127dd7cfb44dd90cc5cb07cd66
